name: Test Action

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create test directories and files
        run: |
          mkdir -p _posts_commit
          mkdir -p _enhance_policy
          mkdir -p _prompts
          echo "You are a test assistant." > _prompts/default_boilerplate.prompt
          echo "Summarize for techies." > _enhance_policy/tech_summary.txt

      - name: Create test posts
        run: |
          # To be enhanced
          echo '---
          title: Test To Enhance
          enhance_policy: tech_summary.txt
          ---
          This post should be enhanced.' > _posts_commit/test-to-enhance.md

          # To be skipped (empty policy)
          echo '---
          title: Test Empty Policy
          enhance_policy:
          ---
          This post should not be enhanced.' > _posts_commit/test-empty-policy.md

          # To be skipped (already enhanced)
          echo '---
          title: Test Already Enhanced
          ---
          This is new content. {% comment %} This post is already enhanced. {% endcomment %}' > _posts_commit/test-already-enhanced.md

      - name: Run action script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: python main.py

      - name: Verify enhanced file
        run: |
          original_text="This post should be enhanced."
          new_filepath="_posts/test-to-enhance.md"
          if ! grep -Pzo "{% comment %}(\s|.)*${original_text}(\s|.)*{% endcomment %}" "$new_filepath"; then exit 1; fi

      - name: Verify skipped file (empty policy)
        run: |
          original_text="This post should not be enhanced."
          new_filepath="_posts/test-empty-policy.md"
          if ! grep -q "$original_text" "$new_filepath"; then exit 1; fi
          if grep -q "{% comment %}" "$new_filepath"; then exit 1; fi

      - name: Verify skipped file (already enhanced)
        run: |
          original_text="This post is already enhanced."
          new_filepath="_posts/test-already-enhanced.md"
          if ! grep -q "$original_text" "$new_filepath"; then exit 1; fi
